apiVersion: v1
kind: LimitRange
metadata:
  name: tdmi-limit-range-mem-cpu-per-container
  namespace: tdmi
spec:
  limits:
  - default:
      cpu: "600m"
      memory: "100Mi"

    defaultRequest:
      cpu: "100m"
      memory: "50Mi"

    max:
      cpu: "1000m"
      memory: "200Mi"

    min:
      cpu: "10m"
      memory: "10Mi"

    type: Container