apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"policy-agent","namespace":"azure-policy"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"policy-agent"},"subjects":[{"kind":"ServiceAccount","name":"azure-policy","namespace":"kube-system"}]}
    creationTimestamp: "2019-11-28T12:34:40Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: policy-agent
    namespace: azure-policy
    resourceVersion: "493"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/azure-policy/rolebindings/policy-agent
    uid: 72cd55c9-11db-11ea-b1ea-5e3eb83808e7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: policy-agent
  subjects:
  - kind: ServiceAccount
    name: azure-policy
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2019-11-28T12:33:47Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-public
    resourceVersion: "138"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-public/rolebindings/system:controller:bootstrap-signer
    uid: 5330fa17-11db-11ea-93fb-62c2765a24cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:bootstrap-signer
  subjects:
  - kind: ServiceAccount
    name: bootstrap-signer
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"default:privileged","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"psp:privileged"},"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"Group","name":"system:masters"},{"apiGroup":"rbac.authorization.k8s.io","kind":"Group","name":"system:serviceaccounts:kube-system"}]}
    creationTimestamp: "2019-11-28T12:34:39Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: default:privileged
    namespace: kube-system
    resourceVersion: "433"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/default:privileged
    uid: 722ab89a-11db-11ea-b1ea-5e3eb83808e7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:privileged
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"kubernetes-dashboard-minimal"},"subjects":[{"kind":"ServiceAccount","name":"kubernetes-dashboard","namespace":"kube-system"}]}
    creationTimestamp: "2020-04-02T10:19:36Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: kubernetes-dashboard
    name: kubernetes-dashboard
    namespace: kube-system
    resourceVersion: "14419742"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/kubernetes-dashboard
    uid: d954ce4e-c1fc-4dbc-a60d-f2f6ea2a0547
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kubernetes-dashboard-minimal
  subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard-minimal","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"kubernetes-dashboard-minimal"},"subjects":[{"kind":"ServiceAccount","name":"kubernetes-dashboard","namespace":"kube-system"}]}
    creationTimestamp: "2019-11-28T12:34:43Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: kubernetes-dashboard
    name: kubernetes-dashboard-minimal
    namespace: kube-system
    resourceVersion: "629"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/kubernetes-dashboard-minimal
    uid: 741c5184-11db-11ea-b1ea-5e3eb83808e7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kubernetes-dashboard-minimal
  subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"metrics-server-auth-reader","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"extension-apiserver-authentication-reader"},"subjects":[{"kind":"ServiceAccount","name":"metrics-server","namespace":"kube-system"}]}
    creationTimestamp: "2019-11-28T12:34:38Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: metrics-server-auth-reader
    namespace: kube-system
    resourceVersion: "358"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/metrics-server-auth-reader
    uid: 719e7b88-11db-11ea-b1ea-5e3eb83808e7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"tunnelfront"},"name":"node-view","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"node-viewer"},"subjects":[{"kind":"ServiceAccount","name":"tunnelfront","namespace":"kube-system"}]}
    creationTimestamp: "2019-11-28T12:34:43Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: tunnelfront
    name: node-view
    namespace: kube-system
    resourceVersion: "640"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/node-view
    uid: 743ed248-11db-11ea-b1ea-5e3eb83808e7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: node-viewer
  subjects:
  - kind: ServiceAccount
    name: tunnelfront
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2020-01-28T11:04:25Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::extension-apiserver-authentication-reader
    namespace: kube-system
    resourceVersion: "6865556"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system::extension-apiserver-authentication-reader
    uid: f1ed03f0-41bd-11ea-bec2-0a72c7f4bb0d
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-controller-manager
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-scheduler
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2019-11-28T12:33:47Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-controller-manager
    namespace: kube-system
    resourceVersion: "6865558"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system::leader-locking-kube-controller-manager
    uid: 5332d41d-11db-11ea-93fb-62c2765a24cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system::leader-locking-kube-controller-manager
  subjects:
  - kind: ServiceAccount
    name: kube-controller-manager
    namespace: kube-system
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-controller-manager
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2019-11-28T12:33:47Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-scheduler
    namespace: kube-system
    resourceVersion: "6865559"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system::leader-locking-kube-scheduler
    uid: 533504b1-11db-11ea-93fb-62c2765a24cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system::leader-locking-kube-scheduler
  subjects:
  - kind: ServiceAccount
    name: kube-scheduler
    namespace: kube-system
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-scheduler
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2019-11-28T12:33:47Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-system
    resourceVersion: "141"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system:controller:bootstrap-signer
    uid: 5339072a-11db-11ea-93fb-62c2765a24cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:bootstrap-signer
  subjects:
  - kind: ServiceAccount
    name: bootstrap-signer
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2019-11-28T12:33:48Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:cloud-provider
    namespace: kube-system
    resourceVersion: "142"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system:controller:cloud-provider
    uid: 533d49c9-11db-11ea-93fb-62c2765a24cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:cloud-provider
  subjects:
  - kind: ServiceAccount
    name: cloud-provider
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2019-11-28T12:33:48Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:token-cleaner
    namespace: kube-system
    resourceVersion: "143"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/system:controller:token-cleaner
    uid: 533f3963-11db-11ea-93fb-62c2765a24cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:token-cleaner
  subjects:
  - kind: ServiceAccount
    name: token-cleaner
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"tunnelfront"},"name":"tunnelfront","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"tunnelfront-secret"},"subjects":[{"kind":"ServiceAccount","name":"tunnelfront","namespace":"kube-system"}]}
    creationTimestamp: "2019-11-28T12:34:43Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: tunnelfront
    name: tunnelfront
    namespace: kube-system
    resourceVersion: "637"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/tunnelfront
    uid: 7438a1af-11db-11ea-b1ea-5e3eb83808e7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: tunnelfront-secret
  subjects:
  - kind: ServiceAccount
    name: tunnelfront
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"typha-cpha","namespace":"kube-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"typha-cpha"},"subjects":[{"kind":"ServiceAccount","name":"typha-cpha","namespace":"kube-system"}]}
    creationTimestamp: "2019-11-28T12:34:37Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: typha-cpha
    namespace: kube-system
    resourceVersion: "313"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/typha-cpha
    uid: 7102fde3-11db-11ea-b1ea-5e3eb83808e7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: typha-cpha
  subjects:
  - kind: ServiceAccount
    name: typha-cpha
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"name":"jenkins-robot-dev-credentials-auth","namespace":"tdmi"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"jenkins-robot-dev-deploy"},"subjects":[{"kind":"ServiceAccount","name":"jenkins-robot-dev","namespace":"tdmi"}]}
    creationTimestamp: "2020-04-08T14:06:45Z"
    name: jenkins-robot-dev-credentials-auth
    namespace: tdmi
    resourceVersion: "15143012"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/tdmi/rolebindings/jenkins-robot-dev-credentials-auth
    uid: da26d6f5-d92b-4981-b277-a2e9b3916a3c
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: jenkins-robot-dev-deploy
  subjects:
  - kind: ServiceAccount
    name: jenkins-robot-dev
    namespace: tdmi
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"creationTimestamp":"2020-01-28T10:20:24Z","name":"psp-cluster-rolebinding","namespace":"tdmi","selfLink":"/apis/rbac.authorization.k8s.io/v1/namespaces/tdmi/rolebindings/psp-cluster-rolebinding","uid":"cc03a71a-41b7-11ea-96aa-2e0d6a4b447c"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"psp-cluster-role"},"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"Group","name":"310af66b-3a8d-4e32-a204-c997c4aa3fd3"},{"apiGroup":"rbac.authorization.k8s.io","kind":"Group","name":"system:serviceaccounts"},{"kind":"ServiceAccount","name":"default","namespace":"tdmi"},{"kind":"ServiceAccount","name":"prometheus-1585866844-node-exporter","namespace":"default"}]}
    creationTimestamp: "2020-01-28T10:20:24Z"
    name: psp-cluster-rolebinding
    namespace: tdmi
    resourceVersion: "14533473"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/tdmi/rolebindings/psp-cluster-rolebinding
    uid: cc03a71a-41b7-11ea-96aa-2e0d6a4b447c
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp-cluster-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: 310af66b-3a8d-4e32-a204-c997c4aa3fd3
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - kind: ServiceAccount
    name: default
    namespace: tdmi
  - kind: ServiceAccount
    name: prometheus-1585866844-node-exporter
    namespace: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
